services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - jo-net

  auth:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - auth-db
      - kafka
      - redis
    networks:
      - jo-net

volumes:
  auth-db-data:

networks:
  jo-net:
    external: true
