app = "bjo-auth"
primary_region = "fra"

[build]

[env]
  # Base de données Postgres via flycast + désactivation TLS
  DATABASE_URL = "postgres://postgres:g8D0D981EC7Xp9D@bjo-auth-db.flycast:5432/auth?sslmode=disable"
  # Redis interne
  REDIS_URL = "redis://bjo-redis.internal:6379"
  # Kafka interne
  KAFKA_BROKERS = "bjo-kafka.internal:9092"
  KAFKA_CLIENT_ID = "auth-service"
  NODE_ENV = "production"
  SEED_ON_START = "false"

[deploy]
  release_command = "npx prisma migrate deploy && npx prisma db seed"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
