# Étape 1 : Build du frontend
FROM node:20-alpine AS build
WORKDIR /app

# Installer dépendances
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Copier le code et builder
COPY . .
RUN npm run build

# Étape 2 : Serveur Nginx
FROM nginx:alpine
# Supprimer la conf par défaut si elle existe
RUN rm -f /etc/nginx/conf.d/default.conf

# Copier la conf SPA
COPY default.dev.conf /etc/nginx/conf.d/default.conf

# Copier le build statique
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port HTTP
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
