# Étape 1 : Build du frontend
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build

# Étape 2 : Serveur Nginx
FROM nginx:alpine
RUN rm -f /etc/nginx/conf.d/default.conf

COPY default.dev.conf /etc/nginx/conf.d/default.conf

# 👉 Copier le build dans /app/ pour correspondre au base path
COPY --from=build /app/dist /usr/share/nginx/html/app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
