networks:
  jo-net:
    external: true

services:
  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    env_file: ./services/payment/.env.production
    environment:
      DATABASE_URL: postgres://postgres:postgres@payment-db:5432/payment
      REDIS_URL: redis://redis:6379
      KAFKA_BROKERS: kafka:9092
    networks: [jo-net]
