services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - jo-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - jo-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - jo-net

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - jo-net

  auth:
    build: ./services/auth
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/.env
    depends_on:
      - auth-db
      - redis
      - kafka
    networks:
      - jo-net

  ticket-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
    volumes:
      - ticket-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - jo-net

  ticketing:
    build: ./services/ticketing
    ports:
      - "3002:3002"
    env_file:
      - ./services/ticketing/.env
    depends_on:
      - ticket-db
      - kafka
    networks:
      - jo-net

  paiement-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paiement
    volumes:
      - paiement-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - jo-net

  paiement:
    build: ./services/paiement
    ports:
      - "3003:3003"
    env_file:
      - ./services/paiement/.env
    depends_on:
      - paiement-db
      - kafka
    networks:
      - jo-net

  verification-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verification
    volumes:
      - verification-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - jo-net

  verification:
    build: ./services/verification
    ports:
      - "3004:3004"
    env_file:
      - ./services/verification/.env
    depends_on:
      - verification-db
      - kafka
    networks:
      - jo-net

  gateway:
    build: ./services/gateway
    ports:
      - "3000:3000"
    env_file:
      - ./services/gateway/.env
    depends_on:
      - auth
      - ticketing
      - paiement
      - verification
    networks:
      - jo-net

volumes:
  auth-db-data:
  ticket-db-data:
  paiement-db-data:
  verification-db-data:

networks:
  jo-net:
    driver: bridge
