services:
  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    env_file: ./services/payment/.env.production
    ports:
      - "3003:3003"
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [jo-net]
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - /app/services/payment/node_modules   # ← protège les deps installées au build

volumes:
  payment_node_modules: {}
