networks:
  bjo-network:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_ticketing_data:

services:
  auth-db:
    image: seleli/postgres-custom:latest
    env_file:
      - .env.development
    ports:
      - "54321:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - bjo-network

  ticketing-db:
    image: seleli/postgres-custom:latest
    env_file:
      - .env.development
    ports:
      - "54322:5432"
    volumes:
      - postgres_ticketing_data:/var/lib/postgresql/data
    networks:
      - bjo-network

  redis:
    image: seleli/redis-custom:latest
    ports:
      - "6379:6379"
    networks:
      - bjo-network

  zookeeper:
    image: seleli/zookeeper-custom:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - bjo-network

  kafka:
    image: seleli/kafka-custom:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - bjo-network

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    image: seleli/billeterie-jo-auth:latest
    env_file:
      - .env.development
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
      - redis
      - kafka
    networks:
      - bjo-network

  ticketing:
    build:
      context: ./services/ticketing
      dockerfile: Dockerfile.dev
    image: seleli/billeterie-jo-ticketing:latest
    env_file:
      - .env.development
    ports:
      - "3002:3002"
    depends_on:
      - ticketing-db
      - redis
      - kafka
    networks:
      - bjo-network

  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile.dev
    image: seleli/billeterie-jo-payment:latest
    env_file:
      - .env.development
    ports:
      - "3003:3003"
    depends_on:
      - redis
      - kafka
    networks:
      - bjo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: seleli/billeterie-jo-frontend:latest
    env_file:
      - .env.development
    ports:
      - "5173:80"
    networks:
      - bjo-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    image: seleli/billeterie-jo-gateway:latest
    env_file:
      - .env.development
    volumes:
      - ./gateway/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - auth
      - ticketing
      - payment
      - frontend
    networks:
      - bjo-network
