
networks:
  jo-net:
    driver: bridge

volumes:
  auth-db-data:
  ticketing-db-data:
  payment-db-data:
  verification-db-data:

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    networks: [jo-net]
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bjo-kafka.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7-alpine
    networks: [jo-net]

  auth-db:
    image: postgres:15
    networks: [jo-net]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  ticketing-db:
    image: postgres:15
    networks: [jo-net]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
    volumes:
      - ticketing-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    networks: [jo-net]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  verification-db:
    image: postgres:15
    networks: [jo-net]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verification
    volumes:
      - verification-db-data:/var/lib/postgresql/data
