
services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-auth:latest

  ticketing:
    build:
      context: ./services/ticketing
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-ticketing:latest

  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-payment:latest

  verification:
    build:
      context: ./services/verification
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-verification:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-frontend:latest

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.prod
    image: seleli/billeterie-jo-gateway:latest
