
networks:
  jo-net:
    external: true

services:
  ticketing:
    build:
      context: .
      dockerfile: services/ticketing/Dockerfile
    env_file: ./services/ticketing/.env.production
    environment:
      DATABASE_URL: postgres://postgres:postgres@ticketing-db:5432/ticketing
      REDIS_URL: redis://redis:6379
      KAFKA_BROKERS: kafka:9092
    networks: [jo-net]
