
services:
  # infra partagée
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - jo-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - jo-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - jo-net

  # --- AUTH ---
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - jo-net

  auth:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
      - kafka
      - redis
    networks:
      - jo-net

  # --- TICKETING ---
  ticketing-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
    volumes:
      - ticketing-db-data:/var/lib/postgresql/data
    networks:
      - jo-net

  ticketing:
    build: ./services/ticketing
    env_file:
      - ./services/ticketing/.env
    ports:
      - "3002:3002"
    depends_on:
      - ticketing-db
      - kafka
      - redis
    networks:
      - jo-net

  # --- PAYMENT ---
  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - jo-net

  payment:
    build: ./services/payment
    env_file:
      - ./services/payment/.env
    ports:
      - "3010:3010"
    depends_on:
      - payment-db
      - kafka
      - redis
    networks:
      - jo-net

volumes:
  auth-db-data:
  ticketing-db-data:
  payment-db-data:

networks:
  jo-net:
    driver: bridge

