services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Identifiant unique du broker
      KAFKA_NODE_ID: 1
      # Rôles : broker + controller
      KAFKA_PROCESS_ROLES: broker,controller
      # Listeners : interne pour Fly.io et contrôleur
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bjo-kafka.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Quorum des contrôleurs (ici 1 seul broker)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Réplication minimale pour un cluster à 1 broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Création auto des topics
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
