services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"   # Broker PLAINTEXT
      - "9093:9093"   # Controller (KRaft)
    environment:
      # Identifiant unique du broker
      KAFKA_NODE_ID: 1
      # Rôles : broker + controller
      KAFKA_PROCESS_ROLES: broker,controller
      # Listeners : écoute sur toutes les interfaces
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Liste visible par les clients
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Quorum des contrôleurs (ici 1 seul broker)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Réplication minimale pour un cluster à 1 broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Création auto des topics
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
