services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: ./frontend/.env.production
    ports:
      - "8080:80"
    networks: [jo-net]
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - /app/frontend/node_modules   # ← protège les deps installées au build

volumes:
  frontend_node_modules: {}
